language: node_js
node_js:
  - "9"
before_install:
  - npm i -g ava
  - npm i -g typescript
  - npm i -g nyc
install:
  - yarn
script:
  - yarn report-test
after_success: npx codecov --file=./coverage/lcov.info