name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 12
    - name: npm install, build, and test
      run: |
        npm install --global yarn
        yarn global add ava@2.4.0
        yarn build
        yarn test
      env:
        CI: true
